version: '3'
services:
  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    env_file: ./.env
    ports:
      - '5000:5000'
    volumes:
      - /home/app/node_modules
      - .:/home/app
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb:/data/db'
volumes:
  mongodb:
